Update build_wheels.yml

diff --git a/.github/workflows/build_wheels.yml b/.github/workflows/build_wheels.yml
--- a/.github/workflows/build_wheels.yml
+++ b/.github/workflows/build_wheels.yml
@@ -128,41 +128,41 @@ jobs:
             make install
             
             # Print to check the files are correctly installed
-            echo "Contents of /usr/local/include/gsl:"
-            ls -la /usr/local/include/gsl/
+            # echo "Contents of /usr/local/include/gsl:"
+            # ls -la /usr/local/include/gsl/
             
-            echo "Contents of /usr/local/include:"
-            ls -la /usr/local/include/
+            # echo "Contents of /usr/local/include:"
+            # ls -la /usr/local/include/
             
-            echo "Contents of /usr/local/lib:"
-            ls -la /usr/local/lib/
+            # echo "Contents of /usr/local/lib:"
+            # ls -la /usr/local/lib/
 
         run: |
-          # Check GSL library and include files
-          if [ -f /usr/lib/x86_64-linux-gnu/libgsl.so ]; then
-            echo "GSL library found in /usr/lib/x86_64-linux-gnu/"
-          else
-            echo "GSL library not found in /usr/lib/x86_64-linux-gnu/"; exit 1;
-          fi
+          # # Check GSL library and include files
+          # if [ -f /usr/lib/x86_64-linux-gnu/libgsl.so ]; then
+          #   echo "GSL library found in /usr/lib/x86_64-linux-gnu/"
+          # else
+          #   echo "GSL library not found in /usr/lib/x86_64-linux-gnu/"; exit 1;
+          # fi
           
-          if [ -f /usr/include/gsl/gsl_sf_bessel.h ]; then
-            echo "GSL include files found in /usr/include/gsl/"
-          else
-            echo "GSL include files not found in /usr/include/gsl/"; exit 1;
-          fi
+          # if [ -f /usr/include/gsl/gsl_sf_bessel.h ]; then
+          #   echo "GSL include files found in /usr/include/gsl/"
+          # else
+          #   echo "GSL include files not found in /usr/include/gsl/"; exit 1;
+          # fi
           
-          # Check FFTW library and include files
-          if [ -f /usr/lib/x86_64-linux-gnu/libfftw3.so ]; then
-            echo "FFTW library found in /usr/lib/x86_64-linux-gnu/"
-          else
-            echo "FFTW library not found in /usr/lib/x86_64-linux-gnu/"; exit 1;
-          fi
+          # # Check FFTW library and include files
+          # if [ -f /usr/lib/x86_64-linux-gnu/libfftw3.so ]; then
+          #   echo "FFTW library found in /usr/lib/x86_64-linux-gnu/"
+          # else
+          #   echo "FFTW library not found in /usr/lib/x86_64-linux-gnu/"; exit 1;
+          # fi
           
-          if [ -f /usr/include/fftw3.h ]; then
-            echo "FFTW include files found in /usr/include/"
-          else
-            echo "FFTW include files not found in /usr/include/"; exit 1;
-          fi
+          # if [ -f /usr/include/fftw3.h ]; then
+          #   echo "FFTW include files found in /usr/include/"
+          # else
+          #   echo "FFTW include files not found in /usr/include/"; exit 1;
+          # fi
           
           python -m cibuildwheel --output-dir wheelhouse
 
