Update build_wheels.yml

diff --git a/.github/workflows/build_wheels.yml b/.github/workflows/build_wheels.yml
--- a/.github/workflows/build_wheels.yml
+++ b/.github/workflows/build_wheels.yml
@@ -359,7 +359,7 @@ jobs:
 
           if [ -d "dist" ] && [ "$(ls -A dist)" ]; then
             echo "Uploading source distribution to PyPI..."
-            twine upload dist/*.tar.gz ||  || echo "Source distribution upload failed, probably cause it's already there continuing..."
+            twine upload dist/*.tar.gz || echo "Source distribution upload failed, probably cause it's already there continuing..."
           else
             echo "No source distribution to upload."
           fi
