Update build_wheels_macos.yml

diff --git a/.github/workflows/build_wheels_macos.yml b/.github/workflows/build_wheels_macos.yml
--- a/.github/workflows/build_wheels_macos.yml
+++ b/.github/workflows/build_wheels_macos.yml
@@ -60,6 +60,19 @@ jobs:
             echo "omp.h not found" && exit 1
           fi
 
+            # Check that gsl_integration.h and fftw3.h are available
+          if [ -f /opt/homebrew/opt/gsl/include/gsl/gsl_integration.h ]; then
+            echo "gsl_integration.h found"
+          else
+            echo "gsl_integration.h not found" && exit 1
+          fi
+          
+          if [ -f /opt/homebrew/opt/fftw/include/fftw3.h ]; then
+            echo "fftw3.h found"
+          else
+            echo "fftw3.h not found" && exit 1
+          fi
+
 
           export LIBRARY_PATH=/opt/homebrew/opt/libomp/lib:$LIBRARY_PATH
           export C_INCLUDE_PATH=/opt/homebrew/opt/libomp/include:$C_INCLUDE_PATH
@@ -71,12 +84,12 @@ jobs:
         if: matrix.os == 'macos-latest'
         env:
           CIBW_ARCHS: "arm64"
-          LDFLAGS: "-L/opt/homebrew/opt/libomp/lib"
-          CPPFLAGS: "-I/opt/homebrew/opt/libomp/include"
-          LIBRARY_PATH: "/opt/homebrew/opt/libomp/lib:$LIBRARY_PATH"
-          C_INCLUDE_PATH: "/opt/homebrew/opt/libomp/include:$C_INCLUDE_PATH"
-          DYLD_LIBRARY_PATH: "/opt/homebrew/opt/libomp/lib:$DYLD_LIBRARY_PATH"
- 
+          LDFLAGS: "-L/opt/homebrew/opt/libomp/lib -L/opt/homebrew/opt/gsl/lib -L/opt/homebrew/opt/fftw/lib"
+          CPPFLAGS: "-I/opt/homebrew/opt/libomp/include -I/opt/homebrew/opt/gsl/include -I/opt/homebrew/opt/fftw/include"
+          LIBRARY_PATH: "/opt/homebrew/opt/libomp/lib:/opt/homebrew/opt/gsl/lib:/opt/homebrew/opt/fftw/lib:$LIBRARY_PATH"
+          C_INCLUDE_PATH: "/opt/homebrew/opt/libomp/include:/opt/homebrew/opt/gsl/include:/opt/homebrew/opt/fftw/include:$C_INCLUDE_PATH"
+          DYLD_LIBRARY_PATH: "/opt/homebrew/opt/libomp/lib:/opt/homebrew/opt/gsl/lib:/opt/homebrew/opt/fftw/lib:$DYLD_LIBRARY_PATH"
+
         run: python -m cibuildwheel --output-dir wheelhouse
 
       - name: Build source distribution (sdist)
